apiVersion: v1
kind: Service
metadata:
  name: noisy-service
  namespace: logpulse
  labels:
    app.kubernetes.io/name: noisy-service
    app.kubernetes.io/component: log-generator
    app.kubernetes.io/part-of: logpulse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: noisy-service
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP